// Login Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

// Logout Constant
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

// Register Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

// Forgot Password Constants
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST'
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS'
export const USER_FORGOT_PASSWORD_FAILED = 'USER_FORGOT_PASSWORD_FAILED'

// User's Profile Constants
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'

// Top Up Constants
export const TOPUP_REQUEST = 'TOPUP_REQUEST'
export const TOPUP_SUCCESS = 'TOPUP_SUCCESS'
export const TOPUP_FAILED = 'TOPUP_FAILED'

// Change Profile Constants
export const CHANGE_PROFILE_REQUEST = 'CHANGE_PROFILE_REQUEST'
export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS'
export const CHANGE_PROFILE_FAILED = 'CHANGE_PROFILE_FAILED'

// Get Restaurants Constants
export const GET_RESTAURANTS_REQUEST = 'GET_RESTAURANTS_REQUEST'
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS'
export const GET_RESTAURANTS_FAILED = 'GET_RESTAURANTS_FAILED'

// Get Restaurant Constants
export const GET_RESTAURANT_REQUEST = 'GET_RESTAURANT_REQUEST'
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS'
export const GET_RESTAURANT_FAILED = 'GET_RESTAURANT_FAILED'

// Get Items Constants
export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED'

// Get Item Constants
export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST'
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAILED = 'GET_ITEM_FAILED'

// Add Item To Cart
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'

// Remove Item To Cart
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'