// Login Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

// Logout Constant
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

// Register Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

// Forgot Password Constants
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST'
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS'
export const USER_FORGOT_PASSWORD_FAILED = 'USER_FORGOT_PASSWORD_FAILED'

// User's Profile Constants
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'

// Top Up Constants
export const TOPUP_REQUEST = 'TOPUP_REQUEST'
export const TOPUP_SUCCESS = 'TOPUP_SUCCESS'
export const TOPUP_FAILED = 'TOPUP_FAILED'

// Change Profile
export const CHANGE_PROFILE_REQUEST = 'CHANGE_PROFILE_REQUEST'
export const CHANGE_PROFILE_SUCCESS = 'CHANGE_PROFILE_SUCCESS'
export const CHANGE_PROFILE_FAILED = 'CHANGE_PROFILE_FAILED'