// Login Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

// Logout Constant
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'